### PR TITLE
 Return the player object onReady

### PR DESCRIPTION
**Pull request by Coriou**
I think it's an easy and also expected behaviour to return the player object in the onReady callback so users can access the API

### CODE REVIEW

**Comment by xDae** [comment]
good point, thanks @Coriou

**Comment by Coriou** [comment]
Thanks for the merge. Would you mind publishing it to NPM too ? I'm currently using your library and it would be easier for me instead of using sym links on my local machine. Thanks !

**Comment by xDae** [comment]
Yep, I will release the new version tomorrow sunday, holidays are hard hehe

**Comment by Coriou** [comment]
Hey, thanks for publishing.

I did find a problem though : the package on NPM only has the README, LICENSE & package.json files, no source files.

Not sure what went wrong, but currently can't install from NPM :

```json
"react-plyr": {
  "version": "2.1.0",
  "resolved": "https://registry.npmjs.org/react-plyr/-/react-plyr-2.1.0.tgz",
  "integrity": "sha512-q5Yxs+mxQY5J+jBrCEoz39aSf82GGZ2AyQj10SJNOFrOor+GQsKuuRqYXWUdybLoHAtq27sKkj4UcNrKU63QUQ==",
  "requires": {
    "plyr": "^3.3.21",
    "prop-types": "^15.6.2"
  }
}
```

**Comment by xDae** [comment]
mmm, thats weird, im going to check, thanks for notice

**Comment by Coriou** [comment]
Hey @xDae - any updates ? Thanks :)

**Comment by Coriou** [comment]
Hello. Tested v2.1.1 from NPM and it's working great. Thanks for the good work !

**Pull request merged**
