### PR TITLE
support audio

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by xDae** [comment]
Hi @benwaffle, thanks por the PR :) 

could you take a look on the failing tests?

**Comment by benwaffle** [comment]
do you want to depend on react 15 or 16? you depend on `react@15` but you import `enzyme-adapter-react-16`

**Comment by benwaffle** [comment]
As for the codeclimate changes, these criteria seem kind of arbitrary. I don't think my code is unclear just because it has 21 functions in a class or 26 lines of code in a function.

**Comment by xDae** [comment]
thanks for the pr @benwaffle, merged!

**Pull request merged**
