### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by mhluska**
- Adds preload prop
- Adds poster to video with sources
- Adds onLoadedData prop
- Adds className prop (makes it possible to handle multiple player refs on one page)
- Fixes key warning (https://github.com/xDae/react-plyr/issues/11)

### CODE REVIEW

**Comment by xDae** [comment]
Wow, thanks @mhluska ! I will take a look and merge it as soon I can 👌🏻👌🏻✌🏻

**Comment by xDae** [comment]
it seems that tests are broken, could you fix to merge? @mhluska

**Comment by mhluska** [comment]
@xDae it's strange, the tests are failing for an area of code that I didn't change:

screenshot 2017-12-04 08 24 07

**Comment by xDae** [comment]
thanks @mhluska, you can check the travisCI test (it looks just the className doesn't match), I will take a look to the Codeclimate problem

**Comment by mhluska** [comment]
Ah the jest test. Ok I updated it.

**Pull request merged**
