### PR TITLE
Bump plyr dependency to 3.2.1

### PR DESCRIPTION
**Pull request by flacerdk**
The latest version of plyr includes several new features and bugfixes. This change bumps the dependency version to `3.2.1` and updates the code to use the new API.

### CODE REVIEW

**Comment by ateich** [comment]
@flacerdk Thanks for updating the plyr dependency 👍 
Changing `src/_snapshots_/App.test.js.snap` to the following fixed the snapshot test errors on my system:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`renders a simple Vimeo Video 1`] = `
<div
  className="react-plyr"
  data-plyr-embed-id="https://vimeo.com/189789787"
  data-plyr-provider="vimeo"
/>
`;

exports[`renders a simple Youtube Video 1`] = `
<div
  className="react-plyr"
  data-plyr-embed-id="CDFN1VatiJA"
  data-plyr-provider="youtube"
/>
`;

```

Alternatively, you could run `jest --updateSnapshots` while in the repo folder, which results in the file above.

If you would make this change, hopefully @xDae will be kind enough to merge it in 😄

**Comment by flacerdk** [comment]
@ateich Thanks for the heads up! I had changed the snapshots manually but they were not matching the tests. They should be correct now.

**Comment by xDae** [comment]
Cool! Thanks for the PR, im going to merge it soon, (on holidays till tomorrow hehe)

**Comment by xDae** [comment]
Merged, i will publish the new version bit later ;)

**Pull request merged**
